# fly.toml app configuration file generated for fly-builder-black-river-7411 on 2023-08-30T18:08:33+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fly-builder-black-river-7411"
primary_region = "hkg"

[build]

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
